@startuml
actor UsuarioNoRegistrado
actor UsuarioRegistrado
boundary "Interfaz Usuario" as InterfazUsuario
control "Gestor Usuario" as GestorUsuario
entity "data_UsuarioRegistrado" as data_UsuarioRegistrado
entity "Perfil Usuario" as PerfilUsuario

UsuarioNoRegistrado -> InterfazUsuario : Registrarse()                                                         
activate InterfazUsuario
InterfazUsuario -> GestorUsuario : Registrarse()
activate GestorUsuario
alt correcto
GestorUsuario -> data_UsuarioRegistrado : create()
activate data_UsuarioRegistrado
data_UsuarioRegistrado -> GestorUsuario : <<return>>
deactivate data_UsuarioRegistrado
GestorUsuario -> InterfazUsuario : <<return>>
deactivate GestorUsuario
deactivate InterfazUsuario
else
GestorUsuario -> InterfazUsuario : error
end

UsuarioNoRegistrado -> InterfazUsuario : ActualizarPerfil()
activate InterfazUsuario
InterfazUsuario -> GestorUsuario : ActualizarPerfil()
activate GestorUsuario
GestorUsuario -> PerfilUsuario : ActualizarPerfil()
activate PerfilUsuario
PerfilUsuario -> GestorUsuario : <<return>>
deactivate PerfilUsuario
GestorUsuario -> InterfazUsuario : <<return>>
deactivate GestorUsuario
deactivate InterfazUsuario

UsuarioNoRegistrado -> InterfazUsuario : EliminarPerfil()
activate InterfazUsuario
InterfazUsuario -> GestorUsuario : EliminarPerfil()
activate GestorUsuario
GestorUsuario -> PerfilUsuario : EliminarPerfil()
activate PerfilUsuario
PerfilUsuario -> GestorUsuario : <<return>>
deactivate PerfilUsuario
GestorUsuario -> InterfazUsuario : <<return>>
deactivate GestorUsuario
deactivate InterfazUsuario

deactivate UsuarioRegistrado
@enduml