@startuml
actor Cliente
boundary "Interfaz Valoracion" as InterfazValoracion
control "Gestor Valoracion" as GestorValoracion
entity "Valoracion" as Valoracion
entity "Comanda" as Comanda
entity "Cocinero" as Cocinero

Cliente -> InterfazValoracion : realizarValoracion(puntualidad, estado, comentario)
activate InterfazValoracion

InterfazValoracion -> GestorValoracion : crearValoracion(puntualidad, estado, comentario)
activate GestorValoracion

GestorValoracion -> Comanda : obtenerResumen()
activate Comanda
Comanda --> GestorValoracion : resumen
deactivate Comanda

GestorValoracion -> Cocinero : obtenerCocineroComanda()
activate Cocinero
Cocinero --> GestorValoracion : cocinero
deactivate Cocinero

GestorValoracion -> Valoracion : crear(puntualidad, estado, comentario, cocinero)
activate Valoracion
Valoracion --> GestorValoracion : OK
deactivate Valoracion

GestorValoracion --> InterfazValoracion : confirmación
deactivate GestorValoracion

deactivate InterfazValoracion

Cliente -> InterfazValoracion : verValoraciones()
activate InterfazValoracion

InterfazValoracion -> GestorValoracion : obtenerValoraciones()
activate GestorValoracion

GestorValoracion -> Valoracion : consultar()
activate Valoracion
loop por cada valoración
    Valoracion --> GestorValoracion : datosValoracion
end
deactivate Valoracion

GestorValoracion --> InterfazValoracion : listaValoraciones
deactivate GestorValoracion

deactivate InterfazValoracion
@enduml


