@startuml
actor Cliente
boundary InterfazComanda
control GestorComanda
entity Comanda
entity Pago
entity PlataformaPago
entity Tarjeta
entity PayPal
entity Cuiner
entity Repartidor
activate Cliente
Cliente -> InterfazComanda : iniciarPagoComanda()
activate InterfazComanda
InterfazComanda -> GestorComanda : iniciarPagoComanda()
activate GestorComanda
GestorComanda -> Comanda : iniciarPagoComanda()
activate Comanda
Comanda -> Pago : procesarPagoComanda()
activate Pago
loop Mientras validarDatos() == false
 Pago -> PlataformaPago : elegirPlataforma(metodo)
    activate PlataformaPago
 alt metodo == "Tarjeta"
        PlataformaPago -> Tarjeta : procesarPagoT()
        activate Tarjeta
        alt Tarjeta.validarDatos() == false
            Tarjeta --> PlataformaPago : error
            PlataformaPago --> Pago : error
            GestorComanda -> InterfazComanda : Error: Datos de tarjeta incorrectos
            deactivate Tarjeta
else Tarjeta.validarDatos() == true
            Tarjeta --> PlataformaPago : procesado()
            PlataformaPago --> Pago : procesado()
            deactivate Tarjeta
            deactivate PlataformaPago
        end
    else metodo == "PayPal"
        PlataformaPago -> PayPal : procesarPagoPP()
        activate PayPal
        alt PayPal.validarDatos() == false
            PayPal --> PlataformaPago : error
            PlataformaPago --> Pago : error
            GestorComanda -> InterfazComanda : Error: Datos de PayPal incorrectos
            deactivate PayPal
        else PayPal.validarDatos() == true
            PayPal --> PlataformaPago : procesado()
            PlataformaPago --> Pago : procesado()
            deactivate PayPal
            deactivate PlataformaPago
 end
 end
end loop
Pago -> Cuiner : procesarPagoCuiner()
activate Cuiner
Cuiner --> Pago : ok
deactivate Cuiner
Pago -> Repartidor : procesarPagoRep()
activate Repartidor
Repartidor --> Pago : ok
deactivate Repartidor
Pago -> PlataformaPago : estadoPago()
PlataformaPago --> Pago : estado
Pago -> Comanda : estadoPago()
deactivate Pago
deactivate Comanda
GestorComanda -> InterfazComanda : pago completado
InterfazComanda -> Cliente : pago completado
deactivate GestorComanda
deactivate InterfazComanda
deactivate Cliente
@enduml
