@startuml
actor Cliente
entity Pedido
control Valoracion
entity Cocinero
boundary ListadoPlatos

activate Cliente

Cliente -> Pedido : consultarPedidoEntregado()
activate Pedido
Pedido --> Cliente : <<return>>
deactivate Pedido

Cliente -> Valoracion : valorarComanda()
activate Valoracion

Valoracion -> Cocinero : asociarValoracion()
activate Cocinero
Cocinero --> Valoracion : <<return>>
deactivate Cocinero

Valoracion -> ListadoPlatos : actualizarPosicionamiento()
activate ListadoPlatos
ListadoPlatos --> Valoracion : <<return>>
deactivate ListadoPlatos

Valoracion --> Cliente : <<return>>
deactivate Valoracion

Cliente -> ListadoPlatos : consultarValoraciones()
activate ListadoPlatos
ListadoPlatos --> Cliente : <<return>>
deactivate ListadoPlatos

deactivate Cliente
@enduml

