@startuml
actor Cliente
control GestorComanda
boundary InterfazComanda
entity Comanda
entity Pago
entity PlataformaPago
entity Tarjeta
entity PayPal
entity Cuiner
entity Repartidor

activate Cliente
Cliente -> Comanda : iniciarPagoComanda()
activate Comanda

Comanda -> Pago : procesarPagoComanda()
activate Pago

Pago -> PlataformaPago : elegirPlataforma()
activate PlataformaPago

alt Metodo == Tarjeta
    PlataformaPago -> Tarjeta : procesarPagoT()
    activate Tarjeta
    return procesado()
    deactivate Tarjeta
else Metodo == PayPal
    PlataformaPago -> PayPal : procesarPagoPP()
    activate PayPal
    return procesado()
    deactivate PayPal
end
deactivate PlataformaPago

Pago -> Cuiner : procesarPagoCuiner()
activate Cuiner
return retorno
deactivate Cuiner

Pago -> Repartidor : procesarPagoRep()
activate Repartidor
return retorno
deactivate Repartidor

PlataformaPago -> Pago : estadoPago()

deactivate Pago

Comanda <- Pago : estadoPago()
deactivate Comanda

Cliente <- Comanda : pago completado
deactivate Cliente
@enduml
