@startuml
left to right direction

actor Cliente
actor Cocinero


  usecase  "Valorar comanda" as us1
  usecase "Asociar valoración al cocinero: ncluir criterios:\npuntualidad, estado del plato" " as us3
  usecase  "Actualizar posición del cocinero" as us4
  usecase "Ver valoraciones antes de pedir" as us5
  usecase "Consultar valoraciones recibidas" as us6

Cliente --> us1
Cliente --> us5

us1  .> us3: include
us3  .> us4 : include
us3  .>  us6 :extend

Cocinero --> us6

@enduml
