@startuml
left to right direction

actor Cliente
actor Cocinero
actor Repartidor

  usecase "Realizar pago de la comanda" as us1
  usecase "Relacionar método de pago\n(Tarjeta / PayPal)" as us2
  usecase "Transferir pagos a cocinero y repartidor" as us3
  usecase "Conectar con plataforma de pago" as us4


Cliente --> us1
Cliente --> us2

us1 --> us2
us2 --> us4
us1 --> us3

Cocinero <-- us3
Repartidor <-- us3

@enduml
