@startuml
left to right direction

actor Cliente
actor Cocinero
actor Repartidor

  usecase "Realizar pago de la comanda Tarjeta / PayPal)" as us2
  usecase "Transferir parte porporcional cocinero y repartidor" as us3


Cliente --> us2

us2  .> us3 : <<include>>
Cocinero <-- us3
Repartidor <-- us3

@enduml
