@startuml

class Cliente <<entity>>
{
   +restriccionesAlimentarias : string
   +elegirVista() : void   
   +buscarCocineroOPlato() : void
   -historial : Pedido
   +mostrarHistorial() : Pedido
}
class Cocinero <<entity>>
{
   -disponibilidad : boolean
   -horaDisponibilidad : string
   +mostrarDisponibilidad() : boolean, string
   +mostrarPlatos() : string
}
class Pedido <<entity>>
{
   +confirmarPedido() : boolean
}
class Platos <<entity>>
{
   +ingredientes : string
   -tiempoEstimadoEntrega : string
   +priorizarPlatos() : void
   +mostrarTiempoEstimadoEntrega() : string
   +mostrarIngredientes() : string
   +modificarPlato() : void
}

class Menú <<comunicació>>
class Buscador <<comunicació>>
class HistorialPedidos <<control>>
Pedido --> Cliente
Pedido --> Cocinero
Platos --> Cliente
Platos --> Cocinero
HistorialPedidos -- Cliente : pertany
Menú "1" o-- "*" Platos
Buscador --> Cliente
@enduml
