@startuml

class Cliente <<boundary>> {
  + iniciarPago()
}

class Comanda <<entity>> {
  + id: String
  + total: Decimal
  + estado: String
}

class Pago <<control>> {
  + identificadorC: String
  + metodo: String
  + estado: String
  + procesar()
}

class Cuiner <<entity>> {
  + compteBancari: String
}

class Repartidor <<entity>> {
  + compteBancari: String
}

class "Tarjeta" <<boundary>> {
  - numero: String
  - caducidad: Data
  - cvv: Codigo
}

class PayPal <<boundary>> {
  + email: String
}

class PlataformaPago <<boundary>> {
  + autenticar()
  + procesarTransaccion()
}

Cliente -> "1..*" Comanda : "Realiza"

Comanda *-- "1" Pago 
Pago ..> PlataformaPago : "Usa" 

Pago o--> Cuiner : "Transfiere su %"
Pago o--> Repartidor : "Transfiere su %"

Tarjeta -up-|> PlataformaPago 
PayPal -up-|> PlataformaPago 

@enduml
