@startuml
class Usuario 
{
   +consultaMenu() : void
}
class "Usuario Registrado" as UsuarioRegistrado
{
   +nombreUsuario : string
   #correuElectronic : string
   +rols : string
   +actualizarPerfil() : void
   +eliminarPerfil() : void
   
}
class "Usuario No Registrado" as UsuarioNoRegistrado
{
   +registrarse() : void
}
class Cliente
{
   +hacerPedido() : void
}
class Cocinero
class Repartidor
class Pedido
class Menú
class ShortcutCorreo
class PerfilUsuario
class Platos

Usuario <|-- UsuarioRegistrado
Usuario <|-- UsuarioNoRegistrado
UsuarioRegistrado <|-- Cliente
UsuarioRegistrado <|-- Cocinero
UsuarioRegistrado <|-- Repartidor
Pedido --> UsuarioRegistrado
Menú --> Usuario
PerfilUsuario -- Usuario : pertany
Platos --o Menú
ShortcutCorreo --> PerfilUsuario


@enduml
