@startuml
class Usuario <<entity>>
{
   +consultaMenu() : void
}
class "data_UsuarioRegistrado" as UsuarioRegistrado <<entity>>
{
   -nombreUsuario : string
   -correuElectronic : string
   -rols : string
   +create() : void   
}
class Cliente <<entity>>
{
   +hacerPedido() : void
}
class "Gestor Usuario" as GestorUsuario <<control>>
{
   +create() : void
   +actualizarPerfil() : void
   +eliminarPerfil() : void
}
class "Interfaz Usuario" as InterfazUsuario <<boundary>>
{
   +registrarse() : void
   +actualizarPerfil() : void
   +eliminarPerfil() : void
}
class Cocinero <<entity>>
class Repartidor <<entity>>
class PerfilUsuario <<entity>>
{
   +actualizarPerfil() : void
   +eliminarPerfil() : void
}


Usuario <|-- UsuarioRegistrado
UsuarioRegistrado <|-- Cliente
UsuarioRegistrado <|-- Cocinero
UsuarioRegistrado <|-- Repartidor
PerfilUsuario "1" -- "1" UsuarioRegistrado : pertany
PerfilUsuario "n" -- "1" GestorUsuario
GestorUsuario "1" -- "1" InterfazUsuario


@enduml
