@startuml
class Usuario <<entity>>
{
   +consultaMenu() : void
}
class "Usuario Registrado" as UsuarioRegistrado <<entity>>
{
   +nombreUsuario : string
   #correuElectronic : string
   +rols : string
   +actualizarPerfil() : void
   +eliminarPerfil() : void
   
}
class "Usuario No Registrado" as UsuarioNoRegistrado <<entity>>
{
   +registrarse() : void
}
class Cliente <<entity>>
{
   +hacerPedido() : void
}
class Cocinero <<entity>>
class Repartidor <<entity>>
class Pedido <<entity>>
class Menú <<boundary>>
class ShortcutCorreo <<boundary>>
class PerfilUsuario <<control>>
class Platos <<entity>>

Usuario <|-- UsuarioRegistrado
Usuario <|-- UsuarioNoRegistrado
UsuarioRegistrado <|-- Cliente
UsuarioRegistrado <|-- Cocinero
UsuarioRegistrado <|-- Repartidor
Pedido --> UsuarioRegistrado
Menú --> Usuario : consulta
PerfilUsuario "1" -- "1" UsuarioRegistrado : pertany
Platos "*" --o "1" Menú
ShortcutCorreo --> UsuarioNoRegistrado : utilitza


@enduml
