@startuml


class Cliente <<entity>> {
  +verValoraciones() : void
  +realizarValoracion() : void
  +verHistorialComandas() : List
}

class "data_Valoracion" as Valoracion <<entity>> {
  - puntuacionPuntualidad : int
  - puntuacionCalidad : int
  - comentario : String
  + calcularMedia() : float
  + mostrarComentario() : String
}

class "data_Comanda" as Comanda <<entity>> {
  - id : int
  - fecha : Date
  - platos : List
  + obtenerResumen() : String
}

class "data_Cocinero" as Cocinero <<entity>> {
  - id : int
  - nombre : String
  + obtenerValoracion() : float
  + mostrarPlatos() : List
}


class "Interfaz Valoracion" as InterfazValoracion <<boundary>> {
  +verValoraciones() : void
  +realizarValoracion(puntualidad: int, estado: int, comentario: String) : void
}


class "Gestor Valoracion" as GestorValoracion <<control>> {
  +crearValoracion(puntualidad: int, estado: int, comentario: String) : void
  +asociarCocinero(comanda: Comanda) : void
  +obtenerValoraciones() : List
}


Cliente --> InterfazValoracion : usa >
InterfazValoracion --> GestorValoracion
GestorValoracion --> Valoracion : crea >
GestorValoracion --> Comanda : consulta >
GestorValoracion --> Cocinero : asocia >

Valoracion --> Cocinero : evalúa >
Valoracion --> Comanda : sobre >

@enduml

