@startuml

class "data_Cocinero" as Cocinero <<entity>>
{
   -disponibilidad : boolean
   -horaDisponibilidad : string
   +mostrarDisponibilidad() : boolean, string
   +mostrarPlatos() : string
   +getPlatos() : Platos
}
class Pedido <<entity>>
{
   -tiempoEntrega : string
   +getTiempoEntrega() : string
   +confirmarPedido() : boolean
}
class Platos <<entity>>
{
   -ingredientes : string
   +mostrarIngredientes() : string
   +modificarPlato() : void
   +getIngredientes() : string
}

class Menú <<boundary>>
{
   +consultaIngredientes() : string
   +eliminaIngredientes() : void
   +consultaPlato(restriccionAlimentaria) : Plato
   +consultaPlatosCocinero(cocinero) : Plato
   +consultaDisponibilidadCocinero(cocinero) : boolean
   +busqueda(nombre,tipo) : Plato o Cocinero
}
class interfazPedido <<boundary>>
{
   +verTiempoEntrega() : string
   +confirmarPedido() : void
   +repetirPedido() : void
   +consultarHistorialPedidos() : void
}
class gestorPedido <<control>>
{
   +getTiempoEntrega() : string
   +confirmarPedido() : void
   +repetirPedido() : void
   +getPedidos() : Pedido
}
class gestorMenu <<control>>
{
   +getIngredientes() : string
   +eliminaIngredientes() : void
   +getPlato() : Plato
   +getPlatosCocinero() : Plato
   +getDispo() : boolean
}
Pedido "n"--"1" gestorPedido
gestorPedido "1"-- "1" interfazPedido
Platos "n" -- "1" Cocinero
Menú "1"--"1" gestorMenu
gestorMenu "1"--"n" Platos
@enduml
