@startuml

class Cliente <<entity>> {
  + estadoPago : char
  + iniciarPagoComanda() : void
}

class Comanda <<entity>> {
  + id: String
  + total: Decimal
  + estado: String
  + procesarPagoComanda() : void
}

class Pago <<control>> {
  + identificadorC: String
  + metodo: String
  + estado: String
  + elegirPlataforma() : void
  + procesarPagoCuiner() : void
  + procesarPagoRep() : void
  + estadoPago() : String
}

class Cuiner <<entity>> {
  + compteBancari: String
}

class Repartidor <<entity>> {
  + compteBancari: String
}

class Tarjeta <<boundary>> {
  - numero: String
  - caducidad: Date
  - cvv: Codigo
  + procesarPagoT() : void
  + validarDatos() : bool
}

class PayPal <<boundary>> {
  + email: String
  - contraseña : String
  + procesarPagoPP() : void
  + validarDatos() : bool
}

class PlataformaPago <<boundary>> {
  + procesado() : void
}


Cliente "1" --> "1..*" Comanda 
Comanda *-- "1" Pago 
Pago ..> PlataformaPago 
Pago o--> Cuiner 
Pago o--> Repartidor 
Tarjeta --|> PlataformaPago 
PayPal --|> PlataformaPago


@enduml
